### ISSUE TITLE
Big gap between profile content and footer

### ISSUE THREAD

**Issue by mileeco** [ysdn-2016/ysdn-2016.github.io#133]
Not quite sure what's happening here... It'd be great to have this gap shorter so that we don't have a big empty space / match the rest of the site! Thanks!!

![screenshot-staging ysdn2016 com 2016-04-10 16-29-05](https://cloud.githubusercontent.com/assets/8468476/14412896/8a317dc4-ff39-11e5-8f58-e7098de9bb15.png)
![screenshot-staging ysdn2016 com 2016-04-10 16-28-54](https://cloud.githubusercontent.com/assets/8468476/14412897/8a34469e-ff39-11e5-8c88-91841a6d6792.png)
![screenshot-staging ysdn2016 com 2016-04-10 16-28-45](https://cloud.githubusercontent.com/assets/8468476/14412898/8a382b24-ff39-11e5-9eaf-a7e0090deb54.png)

**Comment by iamnbutler** [comment]
Seems to be caused by the huge top margin on the footer content. I can remove it but I need to know that it isn't going to impact anything else. @rosszurowski @Emmersonic ? <img width="1440" alt="screenshot 2016-04-11 16 47 09" src="https://cloud.githubusercontent.com/assets/1714999/14441888/0ecae0c2-0005-11e6-9660-aedb128a620e.png">

**Comment by iamnbutler** [comment]
I removed the margin above the footer, but this could probably use some more tightening.

<img width="1440" alt="screenshot 2016-04-11 16 51 36" src="https://cloud.githubusercontent.com/assets/1714999/14442061/ca18efa4-0005-11e6-8c5a-ca202640c5f1.png">

**Comment by rosszurowski** [comment]
Seems fine to remove it. Don't forget to double-check mobile and tablet sizes too.
