### ISSUE TITLE
Shapes should blend "screen" not "multiply"

### ISSUE THREAD

**Issue by rosszurowski** [ysdn-2016/ysdn-2016.github.io#71]

**Comment by iamnbutler** [comment]
Background: CSS shapes are all currently set to multiply because if they are set to screen on a white background they will disappear outside of the blended area.

A few ideas to get this working:
- Look at other blend modes
- Consider stacking 'regular' and screened shapes
- Masking?
- Worst case scenario: Move back to svgs or images

The solution will depend on if the masked shapes need to interact when they move or not (if they move)

**Comment by iamnbutler** [comment]
Solved via using SVGs
