### ISSUE TITLE
Mobile ribbon "Attend the Show" -> "Attend the Grad Show"

### ISSUE THREAD

**Issue by mileeco** [ysdn-2016/ysdn-2016.github.io#87]
![image](https://cloud.githubusercontent.com/assets/8468476/14284951/b64b87cc-fb17-11e5-9030-5b26ea3581e0.png)

The mobile nav still has the older copy. We should change it to "Attend the Grad Show"

**Comment by rosszurowski** [comment]
The text is "Attend the Show" because "Attend the Grad Show" doesn't fit nicely on older phones. 

![screen shot 2016-04-06 at 12 13 40 am](https://cloud.githubusercontent.com/assets/303731/14305676/af828c40-fb8c-11e5-89a1-ff58353ed438.png)

Should we decrease the type size instead to get the full title in there? Or just keep it as "Attend the Show"?

**Comment by rosszurowski** [comment]
Fixed in fdb14c52f057488257a3dc66ae601be0683944cf
